postgresql_databases:
 - name: notesdb # required; the rest are optional
  # port: 5432 # defaults to not set
   owner: postgres # defaults to postgresql_user
  #  login_host: 0.0.0.0 # defaults to 'localhost'
 - name: sonardb # required; the rest are optional
   owner: postgres

# Users to ensure exist.
postgresql_users: 
 - name: postgres #required; the rest are optional
   password: postgres # defaults to not set
   db: notesdb # defaults to not set
  # login_host: '0.0.0.0/0' # defaults to 'localhost'
 