---
- name: deploy war url
  get_url:
    url: file:///vagrant_data/xerfarq2.war
    dest: "{{ tomcat_directory }}//{{ instance.name }}/webapps/"
    validate_certs: no
  when:
    - war.url is defined
