---
- hosts: all
  become: yes
  vars:
    ansible_become_password: vagrant
  vars_files:
    - host_vars/bbdd_vars.yml
  pre_tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'
    - name: update repository
      apt: update_cache=yes cache_valid_time=600 
    - name: install python pip
      apt:
        name: python-pip
    - name: install pymysql and psycopg2 module
      pip: 
        name: pymysql, psycopg2

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.postgresql

  tasks:
    - name: allow external acces
      lineinfile: dest=/etc/postgresql/10/main/postgresql.conf regexp="^#listen_addresses" line="listen_addresses = '*'" state=present backup=yes
      
 